import React from 'react';
import CaixaTexto from '../../components/CaixaTexto'

import './style.css'


function Historia(){
    return(
        <div className='historia-container'>
           <CaixaTexto
           titulo='Sobre a história de Itan'
           texto='Embora essa seja uma história fictícia, o projeto buscou se basear em contextos históricos reais. Podemos imaginar quantas mães, irmãs, filhas e esposas foram arrancadas de seus entes queridos e levadas a força em um navio negreiro durante o período escravista. Esse jogo tem como objetivo mostrar as diversas faces da escravidão na América dentro da perspectiva dos escravizados.'
           />
           <CaixaTexto
           titulo='PISTA 1 - Ganhadeira Joana: "Naquela época era comum escravos venderem quitutes para seus senhores nas praças e ficarem com uma pequena porção dos ganhos para si. Joana era ganhadeira assim como Inaê e estava na praça quando ambos chegaram na Bahia. Ela lembra que Itan foi vendido para alguém que vivia na capital da província."='
           texto='=> Os escravos de ganho eram muitos comuns em centros urbanos. Eles vendiam mercadorias variadas, especialmente verduras, horataliças, peixes, frutas e alimentos feitos por elas. O escravo que trabalhava com ganho, geralmente conseguia juntar dinheiro mais rápido para comprar sua alforria. Conforme a historiadora Cecília Soares, um grande número de escravos de ganhos eram composto por mulheres, uma vez que ganhadeiras africanas eram originárias de regiões na costa ocidental africana, onde o pequeno comércio era tarefa fundamentalmente feminina, assegurando papéis econômicos importantes para as mulheres. O serviço de ganho proporcionava livre trânsito pelas ruas, facilitando a comunicação entre escravos e libertos, o que ampliava suas relações sociais. Ao mesmo tempo, eram vistos como um perigo pela sociedade escravista e as autoridades que temiam revoltas e conflitos.'
           />
           <CaixaTexto
           titulo='PISTA 2 - Ignácio, o vendedor de peixe: "Ignácio vendia peixes quando viu Itan correndo pelo mercado com seu senhor. Ele dizia que iria viajar para um lugar conhecido por seus charutos.  O tráfico de escravos para a América foi proibido desde 1831, embora as décadas de 1840 e 1850 tiveram um grande número de africanos levados para servirem de escravos em países como Brasil e Cuba."='
           texto='=> No Brasil, no começo dos anos 1830, iniciou o processo de proibição do tráfico, que se estendeu até a década de 1850, quando finalmente o tráfico foi finalizado. A Dinamarca já havia abolido o comércio de escravos em 1792, enquanto os Estados Unidos e a Grã-Bretanha decretaram a proibição a partir de 1808. Apesar da proibição do comércio de escravos, Sidney Chalhoub afirma que 42% das importações de africanos para o Brasil desde o século XVI, aconteceram durante o século XIX.  Pierre Verger demonstrou as diversas manobras que traficantes de escravos usaram para burlar a fiscalização nos portos durante o período ilegal, que incluíram desembarques clandestinos em outras regiões do litoral baiano, mudança de bandeira na embarcação e arqueação do navio, carregando capacidade maior ao que realmente tinham. Em 1850, as fazendas de café estavam repletas de trabalhadores reduzidos à condição de escravos ilegalmente. Outros países continuaram recebendo escravizados que saíam da costa africana. O historiador Robin Law afirma que pelo menos até 1857 ainda havia notícias de tráfico em Uidá, até mesmo de escravos vindos de Lagos, ambas na costa ocidental. O comércio negreiro continuou sendo a atividade mais lucrativa na costa africana, mesmo depois da proibição do tráfico, pelo menos até a década de 1860.'
           />
           <CaixaTexto
           titulo='Dica 3 - Esperança, africana liberta: "Esperança viu um menino e seu senhor caminhando pelos portos cubanos com as mesmas descrições que Inaê fez. Parece que estavam a bordo de um navio negreiro. O senhor de Itan levava escravizados para uma região de pampas e criação de gado, lá no Brasil. Parece que Itan era seu ajudante pessoal."'
           texto='=> O comércio de escravos percorria todo o Oceano Atlântico, englobando países como Cuba e Brasil. Era comum o comércio entre países escravistas. Sobre a escravidão em Cuba, os historiadores Rebecca Scott e Jean Hébrard demonstram as relações escravistas no tráfico, cotidiano e demais comércios não só em Cuba, como nos Estados Unidos. Eles analisam a trajetória de uma família inteira, iniciando com a chegada da africana Rosalie na América, até seus descendentes envolvidos no comércio de charuto. Eles demonstram como os libertos precisavam provar sua liberdade constantemente e os medos da reescravização. Outro trabalho importante se refere à resistência escrava em Cuba, realizado pela Historiadora Iacy Maia. / Sobre o tráfico interprovincial, podemos destacar o grande aumento de vendas entre províncias brasileiras após a proibição total do tráfico, em 1850. O arquivo histórico da  Bahia está repleto de pedidos de passaportes acompanhados por carta de compra e venda de escravos para o sul do país.'
           />
           <CaixaTexto
           titulo='DICA 4 - a africana Maria de Jesus: "Maria de Jesus foi levada junto com Itan para o Rio Grande do Sul e vendida para trabalhar como ganhadeira nas ruas da cidade. Ela conta que Itan realmente trabalha diretamente com seu senhor, como ajudante na compra e venda de escravizados. Parece que eles partiram no último navio em direção à terra natal de Itan."='
           texto='=> Os brasileiros mantiveram um intenso comércio com a costa ocidental africana durante o período colonial e também após a Independência, em 1822. Da costa africana, levaram nóz de cola, escravos, dendê, e outras mercadorias para comercializar no Brasil. Desde o século XVII, negociantes levavam tabaco cultivado na Bahia para ser comercializado com os reis e nobres do Daomé.A comunidade instalada na costa africana chamada de agudá foi composta de portugueses, brasileiros e africanos retornados, que conforme alguns estudiosos, utilizavam o catolicismo como marca de distinção social.  A presença de retornados no grande centro comercial da costa ocidental, chamado Uidá, continuou se fortalecendo após os anos de grandes deportações e partidas voluntárias, por conta da Revolta dos Malês, em 1835. '
           />

           <CaixaTexto
           titulo='Relatos reais de africanos libertos pelo transatlântico'
           texto='José Domingues de Abreu teve sua história detalhada nos pedidos de passaportes. Apesar de ser africano, José era cidadão brasileiro, provavelmente devido aos serviços prestados à Pátria. Foi membro do batalhão dos libertos, na luta pela independência do Brasil, entre 1822 e 1823, na Bahia. Mais tarde foi para o Rio de Janeiro, “em defesa da província do Rio Grande do Sul”, em 1828,  já no final da Guerra da Cisplatina, que começou em 1825.  O decreto de 12 de novembro de 1822 criou um batalhão de artilharia composto por pretos libertos,  porém escravos também acabaram inseridos na guerra. Como o africano não apresentou carta de liberdade, não há indícios que comprovem que José tenha sido liberto em consequência de sua participação na guerra. José Domingues deve ter sido um bom soldado, já que foi enviado para outra guerra em 1828, no sul do país. Apesar do Brasil não ter vencido a disputa pela região da Prata, o africano parece ter se fixado em território argentino depois de ser ferido por uma bala, perdendo uma de suas pernas. Em 1853, já na Bahia, na ocasião da solicitação de seu passaporte, José declarou residir em Buenos Aires, casado com uma crioula natural da Argentina, Ana Paula Lima. O africano ainda disse que viajava para Angola, lugar de seu natalício. Embora tenha declarado que residia na Argentina, é possível que o liberto tenha realizado a travessia para uma mudança definitiva ou quem sabe por motivos comerciais, já que declarou no registro que viajava a negócios. Antes de partir, José veio até a Bahia, lugar de onde partiu muitos anos antes. Talvez porque o trânsito para a Costa fosse mais fácil, assim como outros libertos que optaram sair pelos portos baianos. Ou também, porque José não perdeu os vínculos mantidos com a Bahia e sua parada na cidade de Salvador tenha sido no intuito de resgatar velhos contatos. O caso de José Domingues e Ana Paula demonstra a mobilidade desses africanos, não só no Brasil, mas em outros países vizinhos. A escravidão na Argentina foi abolida em 1853, mesmo ano em que o casal viajou para Angola. Também corresponde ao período de tentativa de branqueamento da população no país. George Andrews demonstrou como a documentação para as décadas, a partir de meados de 1830, tendiam a ocultar a cor negra, extinguindo os crioulos, pelo menos no papel, com a mudança do termo “negro” para categorizar a população dita de cor.  O casal provavelmente escolheu um bom momento para viajar rumo ao continente africano, uma vez que a escravidão na Argentina havia sido extinta totalmente e o tráfico com o Brasil finalizado.'
           span='FONTE:  APEB: Seção Colonial -  Fundo Polícia – Correspondência da polícia, pedidos de passaportes – maço 6315.'
           />
        </div>
    )
}


export default Historia